"""add score_templates_table, add created_by field to scores table

Revision ID: 055fdb768732
Revises: b671f4c3310d
Create Date: 2025-06-20 13:44:24.724626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '055fdb768732'
down_revision = 'b671f4c3310d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_templates',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_scores_created_by', 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_constraint('fk_scores_created_by', type_='foreignkey')
        batch_op.drop_column('created_by')

    op.drop_table('score_templates')
    # ### end Alembic commands ###
