"""change password_hash column in users table to 256 length

Revision ID: 176a8657db35
Revises: 591b113b7491
Create Date: 2025-06-17 17:35:07.187241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '176a8657db35'
down_revision = '591b113b7491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
