"""remove username and add gender to users table

Revision ID: 303f5a1eb57a
Revises: 176a8657db35
Create Date: 2025-06-18 17:10:00.257581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303f5a1eb57a'
down_revision = '176a8657db35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=32), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index(batch_op.f('ix_users_gender'), ['gender'], unique=False)
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_index(batch_op.f('ix_users_gender'))
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=1)
        batch_op.alter_column('name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
