"""make created_by field Optional in Score model

Revision ID: 438b07efda2f
Revises: 8b4a83c991f2
Create Date: 2025-07-09 10:02:56.406196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438b07efda2f'
down_revision = '8b4a83c991f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
