"""Remove comment field from ScoreTemplate model

Revision ID: 8b4a83c991f2
Revises: 797a4d7650f6
Create Date: 2025-06-26 12:31:40.517461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b4a83c991f2'
down_revision = '797a4d7650f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_templates', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.VARCHAR(length=256), nullable=False))

    # ### end Alembic commands ###
