"""add unique to name field in ScoreTemplate

Revision ID: ae94b4118426
Revises: 055fdb768732
Create Date: 2025-06-20 15:21:52.304930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae94b4118426'
down_revision = '055fdb768732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_templates_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_templates_name'))

    # ### end Alembic commands ###
