"""remove last_rank field from users table, add user_rank_history table

Revision ID: b671f4c3310d
Revises: cc91b1a0028d
Create Date: 2025-06-20 11:12:44.692262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b671f4c3310d'
down_revision = 'cc91b1a0028d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_rank_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rank_type', sa.String(length=32), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_rank_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_rank_history_rank_type'), ['rank_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_rank_history_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_rank')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_rank', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('user_rank_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_rank_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_rank_history_rank_type'))

    op.drop_table('user_rank_history')
    # ### end Alembic commands ###
